FILES=Action_file.java Action_serveur.java File_attente.java Lecteur.java Redacteur.java main.java Client.java Serveur.java Synchronizer.java 

main : $(FILES)
	javac $(FILES)

clear :
	rm *.class

exec :
	java main
